// <auto-generated />
using System;
using ECommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528021035_AdditionalSeedData")]
    partial class AdditionalSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApp.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AddressLine1 = "12 Nguyen Hue Street",
                            AddressLine2 = "Apartment 8A",
                            City = "Ho Chi Minh City",
                            Country = "Vietnam",
                            CustomerId = 101,
                            PostalCode = "700000",
                            State = "Ho Chi Minh"
                        },
                        new
                        {
                            Id = 102,
                            AddressLine1 = "88 Pasteur Street",
                            AddressLine2 = "Office Reception",
                            City = "Ho Chi Minh City",
                            Country = "Vietnam",
                            CustomerId = 101,
                            PostalCode = "700000",
                            State = "Ho Chi Minh"
                        },
                        new
                        {
                            Id = 103,
                            AddressLine1 = "45 Tran Duy Hung Street",
                            AddressLine2 = "Floor 12",
                            City = "Hanoi",
                            Country = "Vietnam",
                            CustomerId = 102,
                            PostalCode = "100000",
                            State = "Hanoi"
                        },
                        new
                        {
                            Id = 104,
                            AddressLine1 = "19 Ly Thuong Kiet Street",
                            AddressLine2 = "Suite 402",
                            City = "Hanoi",
                            Country = "Vietnam",
                            CustomerId = 102,
                            PostalCode = "100000",
                            State = "Hanoi"
                        },
                        new
                        {
                            Id = 105,
                            AddressLine1 = "7 Bach Dang Street",
                            AddressLine2 = "Unit 3B",
                            City = "Da Nang",
                            Country = "Vietnam",
                            CustomerId = 103,
                            PostalCode = "550000",
                            State = "Da Nang"
                        },
                        new
                        {
                            Id = 106,
                            AddressLine1 = "23 Nguyen Trai Street",
                            AddressLine2 = "Townhouse",
                            City = "Can Tho",
                            Country = "Vietnam",
                            CustomerId = 104,
                            PostalCode = "900000",
                            State = "Can Tho"
                        },
                        new
                        {
                            Id = 107,
                            AddressLine1 = "102 Pine Avenue",
                            AddressLine2 = "Apartment 14C",
                            City = "Seattle",
                            Country = "United States",
                            CustomerId = 105,
                            PostalCode = "98101",
                            State = "Washington"
                        },
                        new
                        {
                            Id = 108,
                            AddressLine1 = "101 Nguyen Van Linh Street",
                            AddressLine2 = "Office Mailroom",
                            City = "Da Nang",
                            Country = "Vietnam",
                            CustomerId = 103,
                            PostalCode = "550000",
                            State = "Da Nang"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cancellation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CancellationCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Cancellations");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CancellationCharges = 0.00m,
                            OrderAmount = 277.98m,
                            OrderId = 104,
                            ProcessedAt = new DateTime(2026, 5, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ProcessedBy = 1,
                            Reason = "Customer requested cancellation before shipment because the delivery address changed.",
                            Remarks = "Approved before fulfillment; full refund issued.",
                            RequestedAt = new DateTime(2026, 5, 15, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = 8
                        },
                        new
                        {
                            Id = 102,
                            CancellationCharges = 0.00m,
                            OrderAmount = 248.98m,
                            OrderId = 105,
                            ProcessedAt = new DateTime(2026, 5, 16, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            ProcessedBy = 1,
                            Reason = "Customer tried to cancel after warehouse packing had started.",
                            Remarks = "Rejected because the order had already entered packing.",
                            RequestedAt = new DateTime(2026, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 9
                        },
                        new
                        {
                            Id = 103,
                            CancellationCharges = 0.00m,
                            OrderAmount = 136.99m,
                            OrderId = 106,
                            ProcessedAt = new DateTime(2026, 5, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcessedBy = 1,
                            Reason = "The customer selected the wrong headphone color.",
                            Remarks = "Approved; refund is waiting for gateway confirmation.",
                            RequestedAt = new DateTime(2026, 5, 17, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 8
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 101,
                            IsCheckedOut = false,
                            UpdatedAt = new DateTime(2026, 5, 20, 10, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 5, 16, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 102,
                            IsCheckedOut = true,
                            UpdatedAt = new DateTime(2026, 5, 16, 8, 22, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 5, 21, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 103,
                            IsCheckedOut = false,
                            UpdatedAt = new DateTime(2026, 5, 21, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CartId = 101,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 1, 0, 0, DateTimeKind.Unspecified),
                            Discount = 7.00m,
                            ProductId = 106,
                            Quantity = 2,
                            TotalPrice = 62.98m,
                            UnitPrice = 34.99m,
                            UpdatedAt = new DateTime(2026, 5, 20, 10, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            CartId = 101,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 18, 0, 0, DateTimeKind.Unspecified),
                            Discount = 1.50m,
                            ProductId = 108,
                            Quantity = 1,
                            TotalPrice = 28.49m,
                            UnitPrice = 29.99m,
                            UpdatedAt = new DateTime(2026, 5, 20, 10, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            CartId = 102,
                            CreatedAt = new DateTime(2026, 5, 16, 8, 11, 0, 0, DateTimeKind.Unspecified),
                            Discount = 13.00m,
                            ProductId = 103,
                            Quantity = 1,
                            TotalPrice = 116.99m,
                            UnitPrice = 129.99m,
                            UpdatedAt = new DateTime(2026, 5, 16, 8, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 104,
                            CartId = 102,
                            CreatedAt = new DateTime(2026, 5, 16, 8, 12, 0, 0, DateTimeKind.Unspecified),
                            Discount = 18.00m,
                            ProductId = 101,
                            Quantity = 1,
                            TotalPrice = 131.99m,
                            UnitPrice = 149.99m,
                            UpdatedAt = new DateTime(2026, 5, 16, 8, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 105,
                            CartId = 103,
                            CreatedAt = new DateTime(2026, 5, 21, 19, 31, 0, 0, DateTimeKind.Unspecified),
                            Discount = 3.00m,
                            ProductId = 3,
                            Quantity = 3,
                            TotalPrice = 56.97m,
                            UnitPrice = 19.99m,
                            UpdatedAt = new DateTime(2026, 5, 21, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 106,
                            CartId = 103,
                            CreatedAt = new DateTime(2026, 5, 21, 19, 33, 0, 0, DateTimeKind.Unspecified),
                            Discount = 6.00m,
                            ProductId = 109,
                            Quantity = 1,
                            TotalPrice = 53.99m,
                            UnitPrice = 59.99m,
                            UpdatedAt = new DateTime(2026, 5, 21, 19, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Name_Unique")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and accessories",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Books and magazines",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Cookware, drinkware, and everyday home essentials",
                            IsActive = true,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Everyday apparel and wardrobe basics",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Skincare, grooming, and personal care products",
                            IsActive = true,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Fitness gear and outdoor activity products",
                            IsActive = true,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Board games, puzzles, and family entertainment",
                            IsActive = true,
                            Name = "Toys & Games"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Email_Unique")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+84900000000"
                        },
                        new
                        {
                            Id = 101,
                            DateOfBirth = new DateTime(1995, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh.nguyen@example.com",
                            FirstName = "Minh",
                            IsActive = true,
                            LastName = "Nguyen",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+84901234567"
                        },
                        new
                        {
                            Id = 102,
                            DateOfBirth = new DateTime(1992, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "an.tran@example.com",
                            FirstName = "An",
                            IsActive = true,
                            LastName = "Tran",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+84909876543"
                        },
                        new
                        {
                            Id = 103,
                            DateOfBirth = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lan.pham@example.com",
                            FirstName = "Lan",
                            IsActive = true,
                            LastName = "Pham",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+84911222333"
                        },
                        new
                        {
                            Id = 104,
                            DateOfBirth = new DateTime(2000, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khoa.le@example.com",
                            FirstName = "Khoa",
                            IsActive = true,
                            LastName = "Le",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+84933444555"
                        },
                        new
                        {
                            Id = 105,
                            DateOfBirth = new DateTime(1997, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.johnson@example.com",
                            FirstName = "Sara",
                            IsActive = true,
                            LastName = "Johnson",
                            Password = "$2b$10$oSRZH.RmBuTu5GhguSMwrumb/jiWlbG/9yhUckKlOhVIarrFMogqi",
                            PhoneNumber = "+12025550178"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Comment = "Fast delivery and the phone battery easily lasts through a busy day.",
                            CreatedAt = new DateTime(2026, 5, 13, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 101,
                            ProductId = 1,
                            Rating = 5,
                            UpdatedAt = new DateTime(2026, 5, 13, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 102,
                            Comment = "The mugs arrived well packed and match the product photos.",
                            CreatedAt = new DateTime(2026, 5, 13, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 101,
                            ProductId = 105,
                            Rating = 4,
                            UpdatedAt = new DateTime(2026, 5, 13, 8, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 103,
                            Comment = "A fun read with a good pace; the bundle was worth adding to my order.",
                            CreatedAt = new DateTime(2026, 5, 9, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 103,
                            ProductId = 3,
                            Rating = 5,
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 104,
                            Comment = "Good grip for home workouts and easy to carry to class.",
                            CreatedAt = new DateTime(2026, 5, 9, 17, 16, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 103,
                            ProductId = 108,
                            Rating = 4,
                            UpdatedAt = new DateTime(2026, 5, 9, 17, 16, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BillingAddressId = 101,
                            CustomerId = 101,
                            OrderDate = new DateTime(2026, 5, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0001",
                            OrderStatus = 4,
                            ShippingAddressId = 102,
                            ShippingCost = 5.00m,
                            TotalAmount = 684.97m,
                            TotalBaseAmount = 749.97m,
                            TotalDiscountAmount = 70.00m
                        },
                        new
                        {
                            Id = 102,
                            BillingAddressId = 103,
                            CustomerId = 102,
                            OrderDate = new DateTime(2026, 5, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0002",
                            OrderStatus = 2,
                            ShippingAddressId = 103,
                            ShippingCost = 0.00m,
                            TotalAmount = 932.78m,
                            TotalBaseAmount = 1089.98m,
                            TotalDiscountAmount = 157.20m
                        },
                        new
                        {
                            Id = 103,
                            BillingAddressId = 105,
                            CustomerId = 103,
                            OrderDate = new DateTime(2026, 5, 14, 18, 5, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0003",
                            OrderStatus = 3,
                            ShippingAddressId = 108,
                            ShippingCost = 7.50m,
                            TotalAmount = 211.08m,
                            TotalBaseAmount = 239.48m,
                            TotalDiscountAmount = 35.90m
                        },
                        new
                        {
                            Id = 104,
                            BillingAddressId = 106,
                            CustomerId = 104,
                            OrderDate = new DateTime(2026, 5, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0004",
                            OrderStatus = 5,
                            ShippingAddressId = 106,
                            ShippingCost = 5.00m,
                            TotalAmount = 277.98m,
                            TotalBaseAmount = 329.98m,
                            TotalDiscountAmount = 57.00m
                        },
                        new
                        {
                            Id = 105,
                            BillingAddressId = 103,
                            CustomerId = 102,
                            OrderDate = new DateTime(2026, 5, 16, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0005",
                            OrderStatus = 2,
                            ShippingAddressId = 104,
                            ShippingCost = 0.00m,
                            TotalAmount = 248.98m,
                            TotalBaseAmount = 279.98m,
                            TotalDiscountAmount = 31.00m
                        },
                        new
                        {
                            Id = 106,
                            BillingAddressId = 101,
                            CustomerId = 101,
                            OrderDate = new DateTime(2026, 5, 17, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0006",
                            OrderStatus = 5,
                            ShippingAddressId = 101,
                            ShippingCost = 5.00m,
                            TotalAmount = 136.99m,
                            TotalBaseAmount = 149.99m,
                            TotalDiscountAmount = 18.00m
                        },
                        new
                        {
                            Id = 107,
                            BillingAddressId = 107,
                            CustomerId = 105,
                            OrderDate = new DateTime(2026, 5, 18, 20, 40, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0007",
                            OrderStatus = 1,
                            ShippingAddressId = 107,
                            ShippingCost = 5.00m,
                            TotalAmount = 72.98m,
                            TotalBaseAmount = 69.98m,
                            TotalDiscountAmount = 2.00m
                        },
                        new
                        {
                            Id = 108,
                            BillingAddressId = 105,
                            CustomerId = 103,
                            OrderDate = new DateTime(2026, 5, 5, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "ORD-2026-0008",
                            OrderStatus = 4,
                            ShippingAddressId = 105,
                            ShippingCost = 5.00m,
                            TotalAmount = 71.47m,
                            TotalBaseAmount = 69.97m,
                            TotalDiscountAmount = 3.50m
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Discount = 70.00m,
                            OrderId = 101,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 629.99m,
                            UnitPrice = 699.99m
                        },
                        new
                        {
                            Id = 102,
                            Discount = 0.00m,
                            OrderId = 101,
                            ProductId = 105,
                            Quantity = 2,
                            TotalPrice = 49.98m,
                            UnitPrice = 24.99m
                        },
                        new
                        {
                            Id = 103,
                            Discount = 150.00m,
                            OrderId = 102,
                            ProductId = 2,
                            Quantity = 1,
                            TotalPrice = 849.99m,
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            Id = 104,
                            Discount = 7.20m,
                            OrderId = 102,
                            ProductId = 102,
                            Quantity = 1,
                            TotalPrice = 82.79m,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 105,
                            Discount = 23.90m,
                            OrderId = 103,
                            ProductId = 104,
                            Quantity = 1,
                            TotalPrice = 95.60m,
                            UnitPrice = 119.50m
                        },
                        new
                        {
                            Id = 106,
                            Discount = 12.00m,
                            OrderId = 103,
                            ProductId = 109,
                            Quantity = 2,
                            TotalPrice = 107.98m,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 107,
                            Discount = 45.00m,
                            OrderId = 104,
                            ProductId = 112,
                            Quantity = 1,
                            TotalPrice = 204.99m,
                            UnitPrice = 249.99m
                        },
                        new
                        {
                            Id = 108,
                            Discount = 12.00m,
                            OrderId = 104,
                            ProductId = 107,
                            Quantity = 1,
                            TotalPrice = 67.99m,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 109,
                            Discount = 13.00m,
                            OrderId = 105,
                            ProductId = 103,
                            Quantity = 1,
                            TotalPrice = 116.99m,
                            UnitPrice = 129.99m
                        },
                        new
                        {
                            Id = 110,
                            Discount = 18.00m,
                            OrderId = 105,
                            ProductId = 101,
                            Quantity = 1,
                            TotalPrice = 131.99m,
                            UnitPrice = 149.99m
                        },
                        new
                        {
                            Id = 111,
                            Discount = 18.00m,
                            OrderId = 106,
                            ProductId = 101,
                            Quantity = 1,
                            TotalPrice = 131.99m,
                            UnitPrice = 149.99m
                        },
                        new
                        {
                            Id = 112,
                            Discount = 2.00m,
                            OrderId = 107,
                            ProductId = 110,
                            Quantity = 1,
                            TotalPrice = 37.99m,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 113,
                            Discount = 0.00m,
                            OrderId = 107,
                            ProductId = 111,
                            Quantity = 1,
                            TotalPrice = 29.99m,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 114,
                            Discount = 2.00m,
                            OrderId = 108,
                            ProductId = 3,
                            Quantity = 2,
                            TotalPrice = 37.98m,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 115,
                            Discount = 1.50m,
                            OrderId = 108,
                            ProductId = 108,
                            Quantity = 1,
                            TotalPrice = 28.49m,
                            UnitPrice = 29.99m
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amount = 684.97m,
                            OrderId = 101,
                            PaymentDate = new DateTime(2026, 5, 10, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            Status = 6,
                            TransactionId = "TXN-CARD-0001"
                        },
                        new
                        {
                            Id = 102,
                            Amount = 932.78m,
                            OrderId = 102,
                            PaymentDate = new DateTime(2026, 5, 12, 14, 33, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "VNPAY",
                            Status = 6,
                            TransactionId = "TXN-VNPAY-0002"
                        },
                        new
                        {
                            Id = 103,
                            Amount = 211.08m,
                            OrderId = 103,
                            PaymentDate = new DateTime(2026, 5, 14, 18, 6, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "COD",
                            Status = 1
                        },
                        new
                        {
                            Id = 104,
                            Amount = 277.98m,
                            OrderId = 104,
                            PaymentDate = new DateTime(2026, 5, 15, 10, 47, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            Status = 10,
                            TransactionId = "TXN-CARD-0004"
                        },
                        new
                        {
                            Id = 105,
                            Amount = 248.98m,
                            OrderId = 105,
                            PaymentDate = new DateTime(2026, 5, 16, 8, 22, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "PayPal",
                            Status = 6,
                            TransactionId = "TXN-PAYPAL-0005"
                        },
                        new
                        {
                            Id = 106,
                            Amount = 136.99m,
                            OrderId = 106,
                            PaymentDate = new DateTime(2026, 5, 17, 12, 12, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Stripe",
                            Status = 6,
                            TransactionId = "TXN-STRIPE-0006"
                        },
                        new
                        {
                            Id = 107,
                            Amount = 72.98m,
                            OrderId = 107,
                            PaymentDate = new DateTime(2026, 5, 18, 20, 41, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            Status = 7,
                            TransactionId = "TXN-FAILED-0007"
                        },
                        new
                        {
                            Id = 108,
                            Amount = 71.47m,
                            OrderId = 108,
                            PaymentDate = new DateTime(2026, 5, 8, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "COD",
                            Status = 6,
                            TransactionId = "COD-RECEIPT-0008"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest model smartphone with advanced features.",
                            DiscountPercentage = 10,
                            ImageUrl = "https://example.com/images/smartphone.jpg",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High-performance laptop suitable for all your needs.",
                            DiscountPercentage = 15,
                            ImageUrl = "https://example.com/images/laptop.jpg",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A thrilling science fiction novel set in the future.",
                            DiscountPercentage = 5,
                            ImageUrl = "https://example.com/images/scifi-novel.jpg",
                            IsAvailable = true,
                            Name = "Science Fiction Novel",
                            Price = 19.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            Description = "Over-ear wireless headphones with active noise cancellation and long battery life.",
                            DiscountPercentage = 12,
                            ImageUrl = "https://example.com/images/wireless-headphones.jpg",
                            IsAvailable = true,
                            Name = "Wireless Noise-Canceling Headphones",
                            Price = 149.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 1,
                            Description = "Compact mechanical keyboard with tactile switches and white backlighting.",
                            DiscountPercentage = 8,
                            ImageUrl = "https://example.com/images/mechanical-keyboard.jpg",
                            IsAvailable = true,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 1,
                            Description = "Multi-port USB-C docking station with HDMI, Ethernet, and fast charging support.",
                            DiscountPercentage = 10,
                            ImageUrl = "https://example.com/images/usb-c-docking-station.jpg",
                            IsAvailable = true,
                            Name = "USB-C Docking Station",
                            Price = 129.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 101,
                            Description = "Durable ten-piece stainless steel cookware set for daily home cooking.",
                            DiscountPercentage = 20,
                            ImageUrl = "https://example.com/images/cookware-set.jpg",
                            IsAvailable = true,
                            Name = "Stainless Steel Cookware Set",
                            Price = 119.50m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 101,
                            Description = "Set of four dishwasher-safe ceramic mugs for coffee, tea, and hot chocolate.",
                            DiscountPercentage = 0,
                            ImageUrl = "https://example.com/images/ceramic-mug-set.jpg",
                            IsAvailable = true,
                            Name = "Ceramic Coffee Mug Set",
                            Price = 24.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 102,
                            Description = "Three-pack of soft cotton crew neck t-shirts for everyday wear.",
                            DiscountPercentage = 10,
                            ImageUrl = "https://example.com/images/cotton-t-shirt-pack.jpg",
                            IsAvailable = true,
                            Name = "Cotton T-Shirt Pack",
                            Price = 34.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 104,
                            Description = "Breathable running shoes with cushioned soles for road training.",
                            DiscountPercentage = 15,
                            ImageUrl = "https://example.com/images/running-shoes.jpg",
                            IsAvailable = true,
                            Name = "Lightweight Running Shoes",
                            Price = 79.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 104,
                            Description = "Lightweight non-slip yoga mat with carrying strap for studio or home workouts.",
                            DiscountPercentage = 5,
                            ImageUrl = "https://example.com/images/yoga-mat.jpg",
                            IsAvailable = true,
                            Name = "Non-Slip Yoga Mat",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 103,
                            Description = "Gentle cleanser, moisturizer, and sunscreen starter kit for daily skincare.",
                            DiscountPercentage = 10,
                            ImageUrl = "https://example.com/images/skincare-starter-kit.jpg",
                            IsAvailable = true,
                            Name = "Skincare Starter Kit",
                            Price = 59.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 105,
                            Description = "Easy-to-learn strategy board game designed for family game nights.",
                            DiscountPercentage = 5,
                            ImageUrl = "https://example.com/images/family-board-game.jpg",
                            IsAvailable = true,
                            Name = "Family Strategy Board Game",
                            Price = 39.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 2,
                            Description = "Three bestselling mystery paperbacks bundled for weekend reading.",
                            DiscountPercentage = 0,
                            ImageUrl = "https://example.com/images/mystery-paperback-collection.jpg",
                            IsAvailable = true,
                            Name = "Mystery Paperback Collection",
                            Price = 29.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 1,
                            Description = "Water-resistant smartwatch with heart-rate tracking and phone notifications.",
                            DiscountPercentage = 18,
                            ImageUrl = "https://example.com/images/smartwatch.jpg",
                            IsAvailable = true,
                            Name = "Smartwatch",
                            Price = 249.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 1,
                            Description = "Previous-generation activity tracker kept unavailable because it is no longer stocked.",
                            DiscountPercentage = 30,
                            ImageUrl = "https://example.com/images/discontinued-fitness-tracker.jpg",
                            IsAvailable = false,
                            Name = "Discontinued Fitness Tracker",
                            Price = 89.99m,
                            StockQuantity = 0
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CancellationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CancellationId")
                        .IsUnique();

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Refunds");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Amount = 277.98m,
                            CancellationId = 101,
                            CompletedAt = new DateTime(2026, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            InitiatedAt = new DateTime(2026, 5, 15, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 104,
                            ProcessedBy = 1,
                            RefundMethod = "Original",
                            RefundReason = "Full refund for approved cancellation before shipment.",
                            Status = 6,
                            TransactionId = "RFND-0001"
                        },
                        new
                        {
                            Id = 102,
                            Amount = 136.99m,
                            CancellationId = 103,
                            InitiatedAt = new DateTime(2026, 5, 17, 13, 5, 0, 0, DateTimeKind.Unspecified),
                            PaymentId = 106,
                            RefundMethod = "Stripe",
                            RefundReason = "Pending refund for approved item color cancellation.",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delivered"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Failed"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Refunded"
                        });
                });

            modelBuilder.Entity("ECommerceApp.Entities.Address", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cancellation", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Order", "Order")
                        .WithOne("Cancellation")
                        .HasForeignKey("ECommerceApp.Entities.Cancellation", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cart", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerceApp.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Feedback", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Product", "Product")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Order", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("Customer");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("ECommerceApp.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Payment", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("ECommerceApp.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Product", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Refund", b =>
                {
                    b.HasOne("ECommerceApp.Entities.Cancellation", "Cancellation")
                        .WithOne("Refund")
                        .HasForeignKey("ECommerceApp.Entities.Refund", "CancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApp.Entities.Payment", "Payment")
                        .WithOne("Refund")
                        .HasForeignKey("ECommerceApp.Entities.Refund", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancellation");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cancellation", b =>
                {
                    b.Navigation("Refund")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApp.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECommerceApp.Entities.Order", b =>
                {
                    b.Navigation("Cancellation")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApp.Entities.Payment", b =>
                {
                    b.Navigation("Refund")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApp.Entities.Product", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
